import pandas as pd

from parsers.data_classes import UserInfo

user_info = pd.DataFrame(data=[[1154,
                                'Unknown',
                                {'Сёнэн': '16', 'Комедия': '14', 'Драма': '13', 'Боевик': '12', 'Фэнтези': '10',
                                 'Школа': '7'},
                                {'toukyou-revengers', 'shingeki-no-kyojin',
                                 'onepunchman', 'horimiya',
                                 'brutal-satsujin-kansatsukan-no-kokuhaku',
                                 'black-clover', 'yakusoku-no-neverland',
                                 'remarried-empress', 'gokushufudou',
                                 'jujutsu-kaisen', 'sssgeubjasalheonteo',
                                 'kuroshitsuji', 'boku_no_hero_academia'},
                                {'haikyu', 'naruto'}
                                ]],
                         columns=['url', 'sex', 'favorite_tags', 'favorite_titles', 'abandoned_titles'])
expectation = UserInfo(2, {'Драма': '97', 'Боевик': '92', 'Приключения': '60', 'Сёнэн': '59', 'Трагедия': '58',
                           'Психология': '58'},
                       {'gantz',
                        'jumyou-wo-kaitotte-moratta-ichinen-ni-tsuki-ichimanen-de',
                        'sakamoto-deizu',
                        'dwaejiuri-',
                        'one-piece',
                        'dungeon-meshi',
                        'ajin', 'berserk',
                        'gyakusatsu-happiendo',
                        'hunter_x_hunter',
                        'yakusoku-no-neverland',
                        'listen-to-futu',
                        'vinland-saga',
                        'kingdom',
                        'goodbye-eri',
                        'chainsaw-man-2',
                        'shuumatsu-no-walkure-shuumatsu-no-valkyrie'},
                       {'jojo-no-kimyou-na-bouken-part-6-stone-ocean-solored',
                        'stand-by-me-my-dear', 'all-you-need-is-kill',
                        'uzumaki', 'blame', 'stone-ocean',
                        'boku_no_hero_academia', 'dai-dark',
                        'shokuryou-jinrui', 'dandadan',
                        'black-clover',
                        'brutal-satsujin-kansatsukan-no-kokuhaku', 'DGray-man',
                        'gokushufudou', 'jojo-no-kimyou-na-bouken-jojorion',
                        'sun-ken-rock', 'enen-no-shouboutai',
                        'toukyou-revengers', 'kimetsu-no-yaiba',
                        'innocent'})
links = pd.DataFrame([1154, 7915, 8161, 8004, 2652, 8778], columns=['url'])
book_example = {'type': 'Манга',
                'tags': {'гг женщина',
                         'гг мужчина',
                         'злые духи',
                         'комедия',
                         'мистика',
                         'монстродевушки',
                         'нежить',
                         'призраки / духи',
                         'сверхъестественное',
                         'сёнэн',
                         'ужасы',
                         'эротика'},
                'ratings': {10: 1083,
                            9: 47,
                            8: 76,
                            7: 26,
                            6: 20,
                            5: 5,
                            4: 14,
                            3: 2,
                            2: 5,
                            1: 32},
                'release_year': '2020',
                'publication_status': 'Онгоинг',
                'translation_status': 'Продолжается',
                'authors': {'eroki'},
                'artists': {'konoshiro shinko'},
                'publishers': {'shogakukan'},
                'chapters_uploaded': '68',
                'age_rating': '18+',
                'release_formats': {'веб'}}
