import pandas as pd

from parsers.data_classes import UserInfo

user_info = pd.DataFrame(data=[[1154,
                                'Unknown',
                                {'Сёнэн': '16', 'Комедия': '14', 'Драма': '13', 'Боевик': '12', 'Фэнтези': '10',
                                 'Школа': '7'},
                                {'https://mangalib.me/toukyou-revengers', 'https://mangalib.me/shingeki-no-kyojin',
                                 'https://mangalib.me/onepunchman', 'https://mangalib.me/horimiya',
                                 'https://mangalib.me/brutal-satsujin-kansatsukan-no-kokuhaku',
                                 'https://mangalib.me/black-clover', 'https://mangalib.me/yakusoku-no-neverland',
                                 'https://mangalib.me/remarried-empress', 'https://mangalib.me/gokushufudou',
                                 'https://mangalib.me/jujutsu-kaisen', 'https://mangalib.me/sssgeubjasalheonteo',
                                 'https://mangalib.me/kuroshitsuji', 'https://mangalib.me/boku_no_hero_academia'},
                                {'https://mangalib.me/haikyu', 'https://mangalib.me/naruto'}
                                ]],
                         columns=['url', 'sex', 'favorite_tags', 'favorite_titles', 'abandoned_titles'])
expectation = UserInfo(2, {'Драма': '97', 'Боевик': '92', 'Приключения': '60', 'Сёнэн': '59', 'Трагедия': '58',
                           'Психология': '58'},
                       {'https://mangalib.me/gantz',
                        'https://mangalib.me/jumyou-wo-kaitotte-moratta-ichinen-ni-tsuki-ichimanen-de',
                        'https://mangalib.me/sakamoto-deizu',
                        'https://mangalib.me/dwaejiuri-',
                        'https://mangalib.me/one-piece',
                        'https://mangalib.me/dungeon-meshi',
                        'https://mangalib.me/ajin', 'https://mangalib.me/berserk',
                        'https://mangalib.me/gyakusatsu-happiendo',
                        'https://mangalib.me/hunter_x_hunter',
                        'https://mangalib.me/yakusoku-no-neverland',
                        'https://mangalib.me/listen-to-futu',
                        'https://mangalib.me/vinland-saga',
                        'https://mangalib.me/kingdom',
                        'https://mangalib.me/goodbye-eri',
                        'https://mangalib.me/chainsaw-man-2',
                        'https://mangalib.me/shuumatsu-no-walkure-shuumatsu-no-valkyrie'},
                       {'https://mangalib.me/jojo-no-kimyou-na-bouken-part-6-stone-ocean-solored',
                        'https://mangalib.me/stand-by-me-my-dear', 'https://mangalib.me/all-you-need-is-kill',
                        'https://mangalib.me/uzumaki', 'https://mangalib.me/blame', 'https://mangalib.me/stone-ocean',
                        'https://mangalib.me/boku_no_hero_academia', 'https://mangalib.me/dai-dark',
                        'https://mangalib.me/shokuryou-jinrui', 'https://mangalib.me/dandadan',
                        'https://mangalib.me/black-clover',
                        'https://mangalib.me/brutal-satsujin-kansatsukan-no-kokuhaku', 'https://mangalib.me/DGray-man',
                        'https://mangalib.me/gokushufudou', 'https://mangalib.me/jojo-no-kimyou-na-bouken-jojorion',
                        'https://mangalib.me/sun-ken-rock', 'https://mangalib.me/enen-no-shouboutai',
                        'https://mangalib.me/toukyou-revengers', 'https://mangalib.me/kimetsu-no-yaiba',
                        'https://mangalib.me/innocent'})
links = pd.DataFrame([1154, 7915, 8161, 8004, 2652, 8778], columns=['url'])
book_example = {'type': 'Манга',
                'tags': {'гг женщина',
                         'гг мужчина',
                         'злые духи',
                         'комедия',
                         'мистика',
                         'монстродевушки',
                         'нежить',
                         'призраки / духи',
                         'сверхъестественное',
                         'сёнэн',
                         'ужасы',
                         'эротика'},
                'ratings': {10: 1083,
                            9: 47,
                            8: 76,
                            7: 26,
                            6: 20,
                            5: 5,
                            4: 14,
                            3: 2,
                            2: 5,
                            1: 32},
                'release_year': '2020',
                'publication_status': 'Онгоинг',
                'translation_status': 'Продолжается',
                'authors': {'eroki'},
                'artists': {'konoshiro shinko'},
                'publishers': {'shogakukan'},
                'chapters_uploaded': '68',
                'age_rating': '18+',
                'release_formats': {'веб'}}
