import pandas as pd

user_info = pd.DataFrame(data=[[1154,
                                'Unknown',
                                {'Сёнэн': '16', 'Комедия': '14', 'Драма': '13', 'Боевик': '12', 'Фэнтези': '10',
                                 'Школа': '7'},
                                {'https://mangalib.me/toukyou-revengers', 'https://mangalib.me/shingeki-no-kyojin',
                                 'https://mangalib.me/onepunchman', 'https://mangalib.me/horimiya',
                                 'https://mangalib.me/brutal-satsujin-kansatsukan-no-kokuhaku',
                                 'https://mangalib.me/black-clover', 'https://mangalib.me/yakusoku-no-neverland',
                                 'https://mangalib.me/remarried-empress', 'https://mangalib.me/gokushufudou',
                                 'https://mangalib.me/jujutsu-kaisen', 'https://mangalib.me/sssgeubjasalheonteo',
                                 'https://mangalib.me/kuroshitsuji', 'https://mangalib.me/boku_no_hero_academia'},
                                {'https://mangalib.me/haikyu', 'https://mangalib.me/naruto'}
                                ]],
                         columns=['url', 'sex', 'favorite_tags', 'favorite_titles', 'abandoned_titles'])
my_user_info = pd.DataFrame(data=[[919160,
                                  'Unknown',
                                  {'Драма': '97', 'Боевик': '92', 'Приключения': '60', 'Сёнэн': '59', 'Трагедия': '58',
                                   'Психология': '58'},
                                  {'https://mangalib.me/gantz', 'https://mangalib.me/berserk',
                                   'https://mangalib.me/jumyou-wo-kaitotte-moratta-ichinen-ni-tsuki-ichimanen-de',
                                   'https://mangalib.me/goodbye-eri', 'https://mangalib.me/one-piece',
                                   'https://mangalib.me/kingdom', 'https://mangalib.me/dwaejiuri-',
                                   'https://mangalib.me/yakusoku-no-neverland', 'https://mangalib.me/sakamoto-deizu',
                                   'https://mangalib.me/gyakusatsu-happiendo', 'https://mangalib.me/chainsaw-man-2',
                                   'https://mangalib.me/vinland-saga', 'https://mangalib.me/hunter_x_hunter',
                                   'https://mangalib.me/shuumatsu-no-walkure-shuumatsu-no-valkyrie',
                                   'https://mangalib.me/ajin', 'https://mangalib.me/dungeon-meshi',
                                   'https://mangalib.me/listen-to-futu'},
                                  {'https://mangalib.me/stand-by-me-my-dear', 'https://mangalib.me/gokushufudou',
                                   'https://mangalib.me/jojo-no-kimyou-na-bouken-part-6-stone-ocean-solored',
                                   'https://mangalib.me/DGray-man',
                                   'https://mangalib.me/dai-dark', 'https://mangalib.me/shokuryou-jinrui',
                                   'https://mangalib.me/innocent',
                                   'https://mangalib.me/stone-ocean',
                                   'https://mangalib.me/brutal-satsujin-kansatsukan-no-kokuhaku',
                                   'https://mangalib.me/toukyou-revengers', 'https://mangalib.me/all-you-need-is-kill',
                                   'https://mangalib.me/kimetsu-no-yaiba', 'https://mangalib.me/boku_no_hero_academia',
                                   'https://mangalib.me/dandadan',
                                   'https://mangalib.me/uzumaki', 'https://mangalib.me/enen-no-shouboutai',
                                   'https://mangalib.me/blame',
                                   'https://mangalib.me/sun-ken-rock',
                                   'https://mangalib.me/jojo-no-kimyou-na-bouken-jojorion',
                                   'https://mangalib.me/black-clover'}
                                  ]],
                            columns=['url', 'sex', 'favorite_tags', 'favorite_titles', 'abandoned_titles'])
links = pd.DataFrame([1154, 7915, 8161, 8004, 2652, 8778], columns=['url'])
